import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    // title: 'Create Next App',
    title: {
        template: '%s | 코딩',
        default: 'Home | 코딩',
    },
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <div style={{ border: '5px solid blue', padding: '10px' }}>
                    <ul>
                        <li className={'cursor-pointer'}>
                            <Link href={'/'} className={'border border-black'}>
                                Home
                            </Link>
                        </li>
                        <li className={'cursor-pointer'}>
                            <Link
                                href={'/client'}
                                className={'border border-black'}
                            >
                                Client
                            </Link>
                        </li>

                        <hr className={'my-5'} />
                    </ul>
                    {children}
                </div>
            </body>
        </html>
    );
}
