import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Link from 'next/link';
import { format } from 'date-fns';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <ul>
                    <li>
                        <Link href={'/'}>Home</Link>
                    </li>
                    <li>
                        <Link href={'/about'}>About</Link>
                    </li>
                    <li>
                        <Link href={'/a'} prefetch={true}>
                            A
                        </Link>
                    </li>
                    <li>
                        <Link href={'/b'} prefetch={true}>
                            B
                        </Link>
                    </li>
                </ul>
                <h2>Layout -&gt; {format(new Date(), 'HH:mm:ss')}</h2>
                {children}
            </body>
        </html>
    );
}
